name: Release 
on: workflow_dispatch

#    release:
#        types: [created,edited]
#    push:
#        branches: [ "main"]
#  repository_dispatch:
#    types: [custom-event-name]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    # Build 
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - uses: actions/upload-artifact@v3
      with:
        name: kramerius-admin
        path: dist-zip/kramerius-admin.zip
    
    # Docker image 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "pavelstastny"
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: pavelstastny/kramerius-admin-client:from-github